# Generated by Django 2.2.13 on 2021-02-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseuser',
            name='email',
            field=models.EmailField(blank=True, default=None, error_messages={'unique': 'A user with this email address already exists.'}, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
